language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t muasif80/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true muasif80/docker-react npm run test
